---
kind: pipeline
type: docker
name: Testing Python CI/CD


steps:
- name: Black Code Format Check
  image: netw0rkaut0mati0n/netauto
  commands:
  - black . --check

- name: Run py_test
  image: netw0rkaut0mati0n/netauto
  environment:
    USER:
      from_secret: USER
    ADMIN_PW:
      from_secret: ADMIN_PW
  commands:
  - python py_test.py
  when:
    branch:
    - master
    - main


trigger:
  branch:
    exclude:
    - pull_request
